version: '3'

services:
  angular:
    image: angular
    container_name: angular
    ports:
      - "4200:80"
    networks:
      - mynetwork
  car:
    image: car
    container_name: car
    ports:
      - "8082:8080"
    networks:
      - mynetwork
  mechanic:
    container_name: mechanic
    image: mechanic
    ports:
      - "8083:8080"
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge